GET http://localhost:8080/api/info/msg

###

POST http://localhost:8080/api/login/signup
Content-Type: application/json

{
  "username": "blubla",
  "password": "davs"
}
###
GET http://localhost:8080/api/info/admin
x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2ODE4ODg5MzQsImlhdCI6MTY4MTg4NzEzNCwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.lEi-i8vwV8pG6jO5Z2DFf64RcRtuTAFxtTcgIIegRig
#x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NjcyOTYyMTAsImlhdCI6MTY2NzI5NDQxMCwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.dlsMNiQc_OYU2HCa-WMzNImQ3qoNy2CGXEWAbXBQM3g"

###
GET http://localhost:8080/api/crud/all

###
POST http://localhost:8080/api/crud/create
Content-Type: application/json

{
  "id": 2,
  "startDate": "22-11-2023",
  "endDate": "23-11-2024",
  "priceAnnual": "30000",
  "deposit": "700",
  "contactPerson": "Hanne"
}

###

PUT http://localhost:8080/api/crud/update/1
Content-Type: application/json

{
    "id": 1,
  "name": "Tester",
  "description": "description"
}
###

