GET http://localhost:8080/api/info/msg

###

POST http://localhost:8080/api/login/signup
Content-Type: application/json

{
  "username": "blubla",
  "password": "davs"
}
###
GET http://localhost:8080/api/info/admin
x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2ODE4ODg5MzQsImlhdCI6MTY4MTg4NzEzNCwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.lEi-i8vwV8pG6jO5Z2DFf64RcRtuTAFxtTcgIIegRig
#x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NjcyOTYyMTAsImlhdCI6MTY2NzI5NDQxMCwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.dlsMNiQc_OYU2HCa-WMzNImQ3qoNy2CGXEWAbXBQM3g"

###
GET http://localhost:8080/api/crud/all

###
POST http://localhost:8080/api/crud/create
Content-Type: application/json

{
  "id": 1,
  "startDate": "24-07-2023",
  "endDate": "27-08-2024",
  "priceAnnual": "60000",
  "deposit": "900",
  "contactPerson": "Blubla",
  "houseid": 1,
  "address": "Hovedgaden 1",
  "city": "København",
  "numberOfRooms": "3"
}

###

PUT http://localhost:8080/api/crud/update/1
Content-Type: application/json

{
    "id": 1,
  "name": "Tester",
  "description": "description"
}
###

PUT http://localhost:8080/api/crud/addTenantToRental
Content-Type: application/json

{
  "rentalId": 1,
  "userName": "user"
}
###
DELETE http://localhost:8080/api/crud/delete/1

###

